version: '3'
services:
  preview:
    build:
      context: .
      args:
        - NODE_ENV=staging
        - REACT_APP_MONGO_URL=${REACT_APP_MONGO_URL}
        - REACT_APP_STRIPE_API_KEY=${REACT_APP_STRIPE_API_KEY}
        - REACT_APP_HUBSPOT_API_KEY=${REACT_APP_HUBSPOT_API_KEY}
    image: cda-app:staging
    restart: always
    labels:
      - "traefik.frontend.rule=Host:cda.cchampou.me"
      - "traefik.backend.port=5000"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"
  production:
    build:
      context: .
      args:
        - NODE_ENV=production
        - REACT_APP_MONGO_URL=${REACT_APP_MONGO_URL}
        - REACT_APP_STRIPE_API_KEY=${REACT_APP_STRIPE_API_KEY}
        - REACT_APP_HUBSPOT_API_KEY={$REACT_APP_HUBSPOT_API_KEY}
    image: cda-app:production
    restart: always
    labels:
      - "traefik.parrainage.frontend.rule=Host:parrainage.confidencesdabeilles.fr"
      - "traefik.parrainagederuches.frontend.rule=Host:parrainagederuches.fr"
      - "traefik.parrainerdesabeilles.frontend.rule=Host:parrainerdesabeilles.fr"
      - "traefik.association.frontend.rule=Host:association.confidencesdabeilles.fr"
      - "traefik.backend.port=5000"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"

networks:
  default:
    external:
      name: layko_layko_net
