version: 2
jobs:
  build & deploy production:
    docker:
      - image: circleci/node:latest

    working_directory: ~/confidences-app

    steps:
      - checkout
      - add_ssh_keys
      - run: yarn
      - run: yarn build
      - run: sudo apt install rsync
      - run: rsync -av -e 'ssh -oStrictHostKeyChecking=no -p 1023' --include ".*" ./build $SSH_USER@$SSH_HOST:/srv/confidences-app
      - run: ssh $SSH_USER@$SSH_HOST -oStrictHostKeyChecking=no -p 1023 '. /home/dev/.zshrc; pm2 reload app'
  
  build & deploy development:
    docker:
      - image: circleci/node:latest

    working_directory: ~/confidences-app

    steps:
      - checkout
      - add_ssh_keys
      - run: npm i
      - run: sudo apt install rsync
      - run: rsync -av -e 'ssh -oStrictHostKeyChecking=no -p 1023' --include ".*" ./* $SSH_USER@$SSH_HOST_DEV:/srv/confidences-app
      - run: ssh $SSH_USER@$SSH_HOST_DEV -oStrictHostKeyChecking=no -p 1023 '. /home/dev/.zshrc; pm2 reload app'


workflows:
  version: 2
  build & deploy:
    jobs:
      - build & deploy production:
          filters:
            branches:
              only:
                - master
      - build & deploy development:
          filters:
            branches:
              only:
                - develop