version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/confidences-app

    steps:
      - checkout
      - run: ssh $SSH_USER@$SSH_HOST -p 1023 'wall "CI in da place"'
    branches:
      only:
        - master
