version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/confidences-app

    steps:
      - checkout
      - add_ssh_keys
      - run: ssh -oStrictHostKeyChecking=no $SSH_USER@$SSH_HOST -p 1023 'cd /srv/confidences-app; git pull'
    branches:
      only:
        - master
